
services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ${PWD}/config.xml:/etc/clickhouse-server/config.xml
      - clickhouse_data_vol:/var/lib/clickhouse
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      nginx-proxy-manager_default:
        ipv4_address: 172.18.0.7

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      nginx-proxy-manager_default:
        ipv4_address: 172.18.0.9

volumes:
  clickhouse_data_vol:
    driver: local
    
networks:
  nginx-proxy-manager_default:
    external: true
    ipam:
      config:
        - subnet: 172.18.0.0/16
